### ISSUE TITLE
Non-minifed JavaScript code?

### ISSUE THREAD

**Issue by Civil** [dotcypress/wterm#8]
It looks like wterm uses xterm.js, but it's not clear which version and how exactly it's used. Theoretically I could've debugged #1 myself, but I'm not that good at JS to work with minified complied JS code, so it would be helpful for debugging purposes to have non-minified version available or even the original source code of js as it is.

**Comment by dotcypress** [comment]
@Civil you can find frontend source code in `/web` folder.
For working with non-minifed version just call: `cd web && npm run dev`
